### ISSUE TITLE
Issue with Expo SDK42

### ISSUE THREAD

**Issue by suzigit** [nandorojo/expo-firestore-offline-persistence#19]
I was very happy using your lib but it seems to have a problem with EXPO SDK42.
I noticed that you are not maintaining the repo anymore and recommending "Expo's New EAS makes it easier to use RN Firebase". 
Are you recommending using Expo with a native use of RN Firebase? I realized that I need to pay 29USD/month to use Expo + EAS with support to native code. Do you know if there is any other option?  Thank you!

**Comment by nandorojo** [comment]
I think you should be able to use `eas build --local` if you don't want to use their build service. 

Maybe reach out to them and see if you can get a free account? Not sure honestly.

> Are you recommending using Expo with a native use of RN Firebase?

Yes, use `@react-native-firebase`, and then use the `with-rn-firebase` config plugin

**Comment by suzigit** [comment]
Thank you for your reply!! Actually, the message error was: 
FirebaseError: You are using the memory-only build of Firestore. Persistence support is only available via the @firebase/firestore bundle or the firebase-firestore.js build.
But I have already installed expo @firebase and imported @firebase/firestore. Since your lib was not updated, I think it is the issue. Have you already confirmed that the lib is not working anymore on Expo 42?

**Comment by nandorojo** [comment]
I'm not sure honestly. This library was just a hack to get persistence to work before expo allowed using Native Firebase, but I don't plan on using or testing it further.

**Comment by nandorojo** [comment]
Notice that the whole lib is just this file https://github.com/nandorojo/expo-firestore-offline-persistence/blob/master/src/polyfill.ts

**Comment by suzigit** [comment]
Great, thank you for your answer!

**Comment by nandorojo** [comment]
No problem
