### ISSUE TITLE
It seems to be a in memory not really persisted right?

### ISSUE THREAD

**Issue by xcarpentier** [nandorojo/expo-firestore-offline-persistence#3]
https://github.com/nandorojo/expo-firestore-offline-persistence/blob/68a860c890dbb3a4f35dd5a37dc8ead46992a38c/src/polyfill.ts#L8

**Comment by nandorojo** [comment]
The local storage here isn’t used. It’s only to keep Firestore from breaking. Firestore uses local storage only to persist across tabs, which isn’t needed for native. This workaround makes an in-memory, fake local storage.

Have you tried this in your app? You’ll notice it works offline.
