### ISSUE TITLE
Remove unused file storage.ts

### ISSUE THREAD

**Issue by harrisonlo** [nandorojo/expo-firestore-offline-persistence#5]
Hi, thanks for the library! Been following the threads on indexeddbshim too. Hope nothing breaks with future releases of Firebase! If so, I'm here to help (my startup depends on this lol). Anyway can you remove that unused file? Thanks.

**Comment by nandorojo** [comment]
Hey sure thing! Using it for mine too. Want to submit a PR removing it?

**Comment by harrisonlo** [comment]
Done!
