### ISSUE TITLE
How to clear persisted indexedDB data to clear this warning:

### ISSUE THREAD

**Issue by jm1200** [nandorojo/expo-firestore-offline-persistence#7]
I have been getting this warning on and off and was hoping someone could help me fix it.

I started getting it after I ran `npm install firebase` instead of `expo install firebase`. I deleted node modules and reinstalled everything as per your documentation but I can't seem to "clear the persisted IndexedDB data" as the warning suggests I do. 

```Error enabling offline persistence. Falling back to persistence disabled: FirebaseError: [code=failed-precondition]: A newer version of the Firestore SDK was previously used and so the persisted data is not compatible with the version of the SDK you are now using. The SDK will operate with persistence disabled. If you need persistence, please re-upgrade to a newer version of the SDK or else clear the persisted IndexedDB data for your app to start fresh.```

**Comment by nandorojo** [comment]
Seems like the version of Firestore probably isn't supported. Honestly not sure about the issue. I'd stick to using `expo install`. Let me know if you find anything online about it though.

**Comment by nandorojo** [comment]
Could you bring up the question [here](https://gist.github.com/zwily/e9e97e0f9f523a72c24c7df01d889482)?
