### ISSUE TITLE
Including this package breaks all my tests

### ISSUE THREAD

**Issue by y2kappa** [nandorojo/expo-firestore-offline-persistence#9]
running 

```
: yarn run test
yarn run v1.22.10
$ mocha -r ts-node/register -r esm tests/**/*.test.ts

../node_modules/react-native/index.js:13
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
       ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

any idea what this could be? Fairly new at js/ts, so it could be user error or lack of knowledge.

**Comment by nandorojo** [comment]
Not sure why you're running mocha instead of React Native, but this isn't related to this library. Looks like a typescript import error.

**Comment by y2kappa** [comment]
they are unit tests, not integration tests. how should I run them? yes, it's a typescript error, I narrowed it down to 'require' being used

**Comment by y2kappa** [comment]
This is the problem - https://github.com/nandorojo/expo-firestore-offline-persistence/blob/master/src/index.ts#L4

How do you run your unit tests if not with `mocha`?
